language: node_js

node_js:
  - "node"
  - "lts/*"
  - "7.6.0"

cache:
  yarn: true
  directories:
    - "node_modules"
    
branches:
  only:
   - master

script:
 - yarn lint
 - yarn coverage
 - yarn report
 - yarn codecov
